version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_SB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=motorola
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql
